# workflow_dispatch allows you to manually trigger a GitHub Actions workflow from the GitHub UI (or via API).
# No push.
# No PR.
# You decide when to run it.
name: This is the first workflow.

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps: 
      - name: This is the first step
        run: echo "Hello Github Actions!!!"
