name: second workflow.

on: 
  push: 
    branches: 
      - main

jobs: 
  second-workflow:
    runs-on: ubuntu-latest
    steps: 
      - name: first step
        run: echo "This workflow will trigger automatically."
